"""membuat table dosen

Revision ID: be782e60c50b
Revises: e4b9568a3be1
Create Date: 2021-06-29 16:43:07.849162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be782e60c50b'
down_revision = 'e4b9568a3be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nim', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('first_lecturer', sa.BigInteger(), nullable=True),
    sa.Column('second_lecturer', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['first_lecturer'], ['dosen.id'], ),
    sa.ForeignKeyConstraint(['second_lecturer'], ['dosen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###
